######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 26 12:38:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
QT += sql network

QMAKE_CXXFLAGS += -std=gnu++0x

# Input
HEADERS += QTap.hpp InVpn.hpp InVpnSslServer.hpp InVpnNode.hpp
SOURCES += main.cpp QTap.cpp InVpn.cpp InVpnSslServer.cpp InVpnNode.cpp
