######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 26 12:38:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QTap.hpp
SOURCES += main.cpp QTap.cpp
